name: Deploy

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Telegram bot dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot==20.0

      - name: Run the Telegram Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          echo "Starting Telegram bot..."
          nohup python Telegram_bot/forward_bot.py &
          BOT_PID=$!
          sleep 21600
          kill $BOT_PID

      - name: Commit and Push Updated User IDs
        if: success()
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add Telegram_bot/user_ids.json
          git commit -m "Update user IDs"
          git push