name: Deploy Telegram Bot

on:
workflow_dispatch
  push:
    branches:
      - main  # Adjust to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Telegram bot dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot==20.0  # Install the required dependencies directly
      - name: Run the Telegram Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python telegram_bot/forward_bot.py