name: Deploy Telegram Bot

on:
  schedule:
    # Run at 00:00, 06:00, 12:00, and 18:00 UTC
    - cron: "0 0 * * *"  # 00:00 to 06:00
    - cron: "0 6 * * *"  # 06:00 to 12:00
    - cron: "0 12 * * *" # 12:00 to 18:00
    - cron: "0 18 * * *" # 18:00 to 24:00
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Telegram bot dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot==20.0

      - name: Run the Telegram Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          echo "Starting Telegram bot for this time window..."
          nohup python telegram_bot/forward_bot.py &
          BOT_PID=$!
          sleep 21600  # Run for 6 hours (21600 seconds)
          echo "Time window completed, stopping bot..."
          kill $BOT_PID  # Stop the bot process